### ISSUE TITLE
Link to *Edit this page* on the docs points to the wrong domain

### ISSUE THREAD

**Issue by tomsaleeba** [jpconstantineau/BlueMicro_BLE#202]
**Describe the bug**
The link to *Edit this page* on the docs points to the wrong domain.

**To Reproduce**
1. Go to docs, e.g: http://bluemicro.jpconstantineau.com/docs/flash
2. Scroll to the bottom and check the URL for the *Edit this page* link

**Expected behavior**
It points to https://github.com/jpconstantineau/BlueMicro_BLE/edit/develop/documentation/docs/flashing_firmware.md or https://github.com/jpconstantineau/BlueMicro_BLE/edit/master/docs/flashing_firmware.md.

**Actual behaviour**
It points to https://github.com/facebook/docusaurus/edit/master/website/docs/flashing_firmware.md, that is, it's still using the Facebook Docusaurus repo.

**Comment by jpconstantineau** [comment]
Indeed. good catch on that.  I'll have to find where that default and update it.

**Comment by jpconstantineau** [comment]
Links are still broken but now point to a 404 on github.

**Comment by tomsaleeba** [comment]
The link has the `docs` dir twice: https://github.com/jpconstantineau/BlueMicro_BLE/tree/documentation-docusaurus/documentation/docs/docs/flashing_firmware.md

If you remove on of them, it works.

**Comment by jpconstantineau** [comment]
Verified the latest push and it's now linked properly.

**Comment by tomsaleeba** [comment]
It's fixed :heart_eyes:
