### ISSUE TITLE
Discord links in README.md "Invite Invalid"

### ISSUE THREAD

**Issue by AkuPython** [jpconstantineau/BlueMicro_BLE#249]
The discord links go to an "Invite Invalid" page.

**Comment by jpconstantineau** [comment]
I just updated the links in the readme page.  Let me know if there is anywhere else you might have found.
I'll close the issue on confirmation or in a few days.

Thanks

**Comment by AkuPython** [comment]
Working now.

Thanks for adding 1.0.0 detail too, that was the first thing I was going to search for on the discord.
