### ISSUE TITLE
Support for nrf52840

### ISSUE THREAD

**Issue by jpconstantineau** [jpconstantineau/BlueMicro_BLE#74]
here are a few tasks that should be done before support for the nrf52840 is possible
1 - detect if the nrf52840 is connected to USB
2 - have the USB HID working
3 - Switch between USB HID and BLE HID automatically when connecting/disconnecting USB connection

The first two steps could be done in the arduino IDE using simple sketches.  Then we can wrap-it for inclusion withing the Firmware.  Use the "arduino_tests" folder to create such test/development scenarios.

**Comment by jpconstantineau** [comment]
For   Point #2, we can use the  tinyusb portions included in the core [here](https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/200b3aaefb3256ac26df82ebc9b5b58923d9c37c/cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/hid/hid_device.h)  There are a number of functions like tud_hid_keyboard_report

**Comment by jpconstantineau** [comment]
for #1, we might be able to use  tud_hid_ready; again from tinyusb

**Comment by JuanAntonioSEP** [comment]
Nice works on the port, looks promising for nextgen BLE 5 DIY keyboards. Was looking for a 65%ish keyboard, with hot-swappable switches and nrf52840 SoC (Usb and Ble). Would hit a sweet spot in my opinion. Low cherry Mx’s with suitably caps and some sort of slim power supply. Could be similar to the  SK621. Don’t know about the switch availability though. Anyhow. Is there a ongoing open source hardware branch like that, with embedded SoC, Pcb antenna, and stuff? If not, there should be. Think one could distribute the Pcb’s as development boards?
